on:
  push:

name: deploy

jobs:

  build-and-deploy:

    runs-on: ubuntu-20

    steps:

      - name: Checkout code
        uses: actions/checkout@master

      - name: An example command
        shell: bash
        run: echo "test works!"